### ISSUE TITLE
[BUG] Broken Sym links breaks app with stack trace

### ISSUE THREAD

**Issue by dhnunes** [dhnunes/pdedup#4]
Hey,

When running against a directory that has broken symbolic links , app just breaks:

$ python pdedup.py -d /home/dnunes                                             
Walking into directory tree...
Traceback (most recent call last):
  File "pdedup.py", line 14, in <module>
    result = file.file_walker()
  File "/home/dnunes/Code/Python/pdedup/Library/filehasher.py", line 64, in file_walker
    if os.path.getsize(os.path.join(root, file)):
  File "/home/dnunes/.virtualenvs/pdedup/lib64/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/home/dnunes/.steampath'

**Comment by dhnunes** [comment]
I've able to reproduce this problem:

$ cd sample-data
$ ls
copy-teste1  teste1  teste2  teste3  teste4  teste5
$ ln -s teste01 link-teste01
$ ll
total 24K
-rw-r--r--. 1 dnunes dnunes 427 Jul 17 11:08 copy-teste1
lrwxrwxrwx. 1 dnunes dnunes   7 Jul 17 11:32 link-teste01 -> teste01
-rw-r--r--. 1 dnunes dnunes 427 Jul 17 11:07 teste1
-rw-r--r--. 1 dnunes dnunes 396 Jul 17 11:07 teste2
-rw-r--r--. 1 dnunes dnunes 400 Jul 17 11:07 teste3
-rw-r--r--. 1 dnunes dnunes 409 Jul 17 11:07 teste4
-rw-r--r--. 1 dnunes dnunes 404 Jul 17 11:07 teste5

$ python pdedup.py -d sample-data

Traceback (most recent call last):
  File "pdedup.py", line 14, in <module>
    result = file.file_walker()
  File "/home/dnunes/Code/Python/pdedup/Library/filehasher.py", line 70, in file_walker
    if os.path.getsize(os.path.join(root, file)):
  File "/home/dnunes/.virtualenvs/pdedup/lib64/python3.7/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'sample-data/link-teste01'
